package org.ihtsdo.snomed.util.rf2.schema;

public interface RF2SchemaConstants {

	// id effectiveTime active moduleId sourceId destinationId relationshipGroup typeId characteristicTypeId modifierId
    Long ISA_ID = 116680003L;
	Long SNOMED_ROOT_CONCEPT = 138875005L;
	String CHARACTERISTIC_STATED_SCTID = "900000000000010007";
	String FIELD_DELIMITER = "\t";
	String LINE_DELIMITER = "\r\n";
	String ACTIVE_FLAG = "1";
	String INACTIVE_FLAG = "0";
	String HEADER_ROW = "id\teffectiveTime\tactive\tmoduleId\tsourceId\tdestinationId\trelationshipGroup\ttypeId\tcharacteristicTypeId\tmodifierId\r\n";

	int NOT_SET = -1;
	int IMMEDIATE_CHILD = 1;
	int NA = -1;
	String FSN = "900000000000003001";
	String FULLY_DEFINED_SCTID = "900000000000073002";
	String FULLY_SPECIFIED_NAME = "900000000000003001";
	String ADDITIONAL_RELATIONSHIP = "900000000000227009";
	String SPACE = " ";
	String COMMA = ",";
	String COMMA_QUOTE = ",\"";
	String QUOTE_COMMA = "\",";
	String QUOTE_COMMA_QUOTE = "\",\"";
	String TAB = "\t";
	String CSV_FIELD_DELIMITER = COMMA;
	String TSV_FIELD_DELIMITER = TAB;
	String QUOTE = "\"";
	String INGREDIENT_SEPARATOR = "+";
	String INGREDIENT_SEPARATOR_ESCAPED = "\\+";
	
	enum RF2_FILE { CONCEPT, STATED, INFERRED, LANGUAGE, DESCRIPTION }

    enum PartionIdentifier {CONCEPT, DESCRIPTION, RELATIONSHIP}

    enum InactivationIndicator {DUPLICATE, OUTDATED, ERRONEOUS, LIMITED, MOVED_ELSEWHERE,
		PENDING_MOVE, INAPPROPRIATE, CONCEPT_NON_CURRENT, RETIRED}

    String GB_ENG_LANG_REFSET = "900000000000508004";
	String US_ENG_LANG_REFSET = "900000000000509007";
	
	String SEMANTIC_TAG_START = "(";
	
	enum CHARACTERISTIC { STATED, INFERRED, QUALIFYING, ADDITIONAL, ALL}

    String SCTID_STATED_RELATIONSHIP = "900000000000010007";
	String SCTID_INFERRED_RELATIONSHIP = "900000000000011006";
	String SCTID_QUALIFYING_RELATIONSHIP = "900000000000225001";
	String SCTID_ADDITIONAL_RELATIONSHIP = "900000000000227009";
	
	enum DEFINITION_STATUS { PRIMITIVE, FULLY_DEFINED }

    enum MODIFER { EXISTENTIAL, UNIVERSAL}

    String SCTID_EXISTENTIAL_MODIFIER = "900000000000451002";
	String SCTID_UNIVERSAL_MODIFIER = "900000000000450001";

	enum ACTIVE_STATE { ACTIVE, INACTIVE, BOTH }

    enum ACCEPTABILITY { ACCEPTABLE, PREFERRED }

    enum CARDINALITY { AT_LEAST_ONE, EXACTLY_ONE }

    enum DESCRIPTION_TYPE { FSN, SYNONYM, DEFINTION }


    // Relationship columns
    int REL_IDX_ID = 0;
	int REL_IDX_EFFECTIVETIME = 1;
	int REL_IDX_ACTIVE = 2;
	int REL_IDX_MODULEID = 3;
	int REL_IDX_SOURCEID = 4;
	int REL_IDX_DESTINATIONID = 5;
	int REL_IDX_RELATIONSHIPGROUP = 6;
	int REL_IDX_TYPEID = 7;
	int REL_IDX_CHARACTERISTICTYPEID = 8;
	int REL_IDX_MODIFIERID = 9;
	int REL_MAX_COLUMN = 9;

	// Concept columns
	// id effectiveTime active moduleId definitionStatusId
    int CON_IDX_ID = 0;
	int CON_IDX_EFFECTIVETIME = 1;
	int CON_IDX_ACTIVE = 2;
	int CON_IDX_MODULID = 3;
	int CON_IDX_DEFINITIONSTATUSID = 4;

	// Description columns
	// id effectiveTime active moduleId conceptId languageCode typeId term caseSignificanceId
    int DES_IDX_ID = 0;
	int DES_IDX_EFFECTIVETIME = 1;
	int DES_IDX_ACTIVE = 2;
	int DES_IDX_MODULID = 3;
	int DES_IDX_CONCEPTID = 4;
	int DES_IDX_LANGUAGECODE = 5;
	int DES_IDX_TYPEID = 6;
	int DES_IDX_TERM = 7;
	int DES_IDX_CASESIGNIFICANCEID = 8;

}
